/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-09 16:12:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("      \r\n");
      out.write("    </head>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        <!--\r\n");
      out.write("        body,td,div,p,a,font,span {font-family: arial,sans-serif}\r\n");
      out.write("\r\n");
      out.write("        #highlight\r\n");
      out.write("        {\r\n");
      out.write("            float:left;\r\n");
      out.write("            padding-top:0.6em;\r\n");
      out.write("            margin:2em 2em 0 0;\r\n");
      out.write("            border-top:1px solid #ddd;\r\n");
      out.write("            min-width:160px\r\n");
      out.write("        }\r\n");
      out.write("        #highlight h2\r\n");
      out.write("        { font-size:1em;\r\n");
      out.write("          margin:0 0 0.2em\r\n");
      out.write("        }\r\n");
      out.write("        .time\r\n");
      out.write("        { color:#999;\r\n");
      out.write("          margin:0;\r\n");
      out.write("          display:inline;\r\n");
      out.write("          padding:0 0 0 0.8em;\r\n");
      out.write("        }\r\n");
      out.write("        .post\r\n");
      out.write("        {\r\n");
      out.write("            padding:0;\r\n");
      out.write("            padding-top:2px;\r\n");
      out.write("        }\r\n");
      out.write("        .snippet\r\n");
      out.write("        {\r\n");
      out.write("            margin:0.3em 0 0\r\n");
      out.write("        }\r\n");
      out.write("        .feed-heading\r\n");
      out.write("        {\r\n");
      out.write("            color:#999;\r\n");
      out.write("            float:left;\r\n");
      out.write("            margin:1.05em 0.3em 0 0\r\n");
      out.write("        }\r\n");
      out.write("        #feed-icons\r\n");
      out.write("        {\r\n");
      out.write("            list-style:none;\r\n");
      out.write("            margin:1em 0 0; padding:0; text-indent:-10000px; overflow:hidden }\r\n");
      out.write("        #feed-icons li\r\n");
      out.write("        {\r\n");
      out.write("            width:16px;\r\n");
      out.write("            height:16px;\r\n");
      out.write("            float:left;\r\n");
      out.write("            margin-right:0.5em\r\n");
      out.write("        }\r\n");
      out.write("        #feed-icons li a\r\n");
      out.write("        {\r\n");
      out.write("            display:block;\r\n");
      out.write("            width:16px;\r\n");
      out.write("            height:16px;\r\n");
      out.write("            background-image:url(//www.google.com/images/icons/feature/sprite_mail_hp.png);\r\n");
      out.write("            background-repeat:no-repeat\r\n");
      out.write("        }\r\n");
      out.write("        .feed-blogger a\r\n");
      out.write("        {\r\n");
      out.write("            background-position: -16px -168px;\r\n");
      out.write("        }\r\n");
      out.write("        .feed-twitter a\r\n");
      out.write("        {\r\n");
      out.write("            background-position: 0 -168px;\r\n");
      out.write("        }\r\n");
      out.write("        .feed-facebook a\r\n");
      out.write("        {\r\n");
      out.write("            background-position: 0 -184px;\r\n");
      out.write("        }\r\n");
      out.write("        .feed-buzz a\r\n");
      out.write("        {\r\n");
      out.write("            background-position: 0 -200px\r\n");
      out.write("        }\r\n");
      out.write("        .feed-rss a\r\n");
      out.write("        {\r\n");
      out.write("            background-position: -16px -184px;\r\n");
      out.write("        }\r\n");
      out.write("        //-->\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <form  action=\"LoginProcess.jsp\" method=\"get\">\r\n");
      out.write("        <table width=94% border=0 align=center cellpadding=0 cellspacing=0>\r\n");
      out.write("            <tr valign=top>\r\n");
      out.write("                <td width=1%>\r\n");
      out.write("                    \r\n");
      out.write("                </td>\r\n");
      out.write("                <td width=99% bgcolor=#ffffff valign=top>\r\n");
      out.write("                    <table width=100% cellpadding=1>\r\n");
      out.write("                        <tr valign=bottom>\r\n");
      out.write("\r\n");
      out.write("                            <td><div align=right>&nbsp;</div></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <table width=94% align=\"center\"cellpadding=5 cellspacing=1>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=75% valign=top><h1>Welcome to Online Address Book.</h1>\r\n");
      out.write("                <p class=\"intro\" style=\"text-align:left\"><font size=-1>The Online Address Book is a tool intended to be used by  evereybody and which is very helpful to store details of users and friends of users.:</font></p>\r\n");
      out.write("              <font size=-1>\r\n");
      out.write("                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"95%\">\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td class=\"feature-image\"><div class=\"SPRITE_storage\" /></td>\r\n");
      out.write("                      <td class=\"feature-description\"><font size=-1>\r\n");
      out.write("                        <li><b>My Profile</b><br>\r\n");
      out.write("                          This <span id=quota>helps</span> to view the details of the users</li>\r\n");
      out.write("                      </font> </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td class=\"feature-image\"><div class=\"SPRITE_spam_new\" /></td>\r\n");
      out.write("                      <td class=\"feature-description\"><font size=-1>\r\n");
      out.write("                        <li><b>My Attachments</b><br>\r\n");
      out.write("                          This is useful to add the attacments in your account.<br>\r\n");
      out.write("                          <!-- End-user will be able to ostpone the scheduled event.<br> -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </font> </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td class=\"feature-image\"><div class=\"SPRITE_cell\" /></td>\r\n");
      out.write("                      <td class=\"feature-description\"><font size=-1>\r\n");
      out.write("                        <li><b>Phone Book</b><br>\r\n");
      out.write("                          This is useful to store the mobile numbers <br/></li>\r\n");
      out.write("                      </font></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                   <!--  <tr>\r\n");
      out.write("                      <td class=\"feature-image\"><div class=\"SPRITE_cell\" /></td>\r\n");
      out.write("                      <td class=\"feature-description\"><font size=-1>\r\n");
      out.write("                        <li><b>Calander</b><br>\r\n");
      out.write("                          The mail composing is done.<br>\r\n");
      out.write("                          Once mails composed can be sent from this part of the module.<br>\r\n");
      out.write("                          The drafted mails can be saved.</li>\r\n");
      out.write("                      </font> </td>\r\n");
      out.write("                    </tr> -->\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div id=\"highlight\"> <font size='-1'>&nbsp; </font></div>\r\n");
      out.write("              </font></td>\r\n");
      out.write("            <td valign=top><!-- login box -->\r\n");
      out.write("                <div id=login>\r\n");
      out.write("                  <style type=\"text/css\">\r\n");
      out.write("          <!--\r\n");
      out.write("                                            div.errormsg\r\n");
      out.write("                                            {\r\n");
      out.write("                                                color: red; font-size: smaller;\r\n");
      out.write("                                                font-family:arial,sans-serif;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            font.errormsg\r\n");
      out.write("                                            {\r\n");
      out.write("                                                color: red;\r\n");
      out.write("                                                font-size: smaller;\r\n");
      out.write("                                                font-family:arial,sans-serif;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            -->\r\n");
      out.write("                                        </style>\r\n");
      out.write("                  <style type=\"text/css\">\r\n");
      out.write("          <!--\r\n");
      out.write("                                            .gaia.le.lbl\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("                                                font-size: smaller;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            .gaia.le.fpwd\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("                                                font-size: 70%;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            .gaia.le.chusr\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("                                                font-size: 70%;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            .gaia.le.val\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("                                                font-size: smaller;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            .gaia.le.button\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("                                                font-size: smaller;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            .gaia.le.rem\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("                                                font-size: smaller;\r\n");
      out.write("                                            }\r\n");
      out.write("\r\n");
      out.write("                                            .gaia.captchahtml.desc\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: arial, sans-serif;\r\n");
      out.write("                                                font-size: smaller;\r\n");
      out.write("                                            }\r\n");
      out.write("                                            .gaia.captchahtml.cmt\r\n");
      out.write("                                            {\r\n");
      out.write("                                                font-family: arial, sans-serif;\r\n");
      out.write("                                                font-size: smaller;\r\n");
      out.write("                                                font-style: italic;\r\n");
      out.write("                                            }\r\n");
      out.write("\r\n");
      out.write("                                            -->\r\n");
      out.write("          </style>\r\n");
      out.write("                    <div id=\"gaia_loginbox\">\r\n");
      out.write("                      <table align=\"left\" class=\"form-noindent\" cellspacing=\"3\" cellpadding=\"5\" width=\"100%\" border=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td valign=\"top\" style=\"text-align:center\" nowrap=\"nowrap\"\r\n");
      out.write("                                                            bgcolor=\"#e8eefa\"><input type=\"hidden\" name=\"ltmpl\"\r\n");
      out.write("                                                                   value=\"default\">\r\n");
      out.write("                              <input type=\"hidden\" name=\"ltmplcache\"\r\n");
      out.write("                                                                   value=\"2\">\r\n");
      out.write("                              <div class=\"loginBox\">\r\n");
      out.write("                                <table width=\"250\" height=\"248\" border=\"0\" align=\"center\" cellpadding=\"1\" cellspacing=\"0\" bgcolor=\"#c2bddd\" id=\"gaia_table\" bordercolor=\"#666666\">\r\n");
      out.write("                                  <tr>\r\n");
      out.write("                                    <td colspan=\"2\" align=\"center\"><font size=\"-1\"> Sign in with your </font>\r\n");
      out.write("                                        <table >\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td valign=\"top\"></td>\r\n");
      out.write("                                            <td valign=\"middle\"><font size=\"+0\"><b>Account</b></font> </td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                      </table></td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                  <tr>\r\n");
      out.write("                                    <td colspan=\"2\" align=\"center\"></td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                  <tr id=\"email-row\">\r\n");
      out.write("                                    <td nowrap=\"nowrap\"><div align=\"right\"> <span class=\"gaia le lbl\"> Username: </span> </div></td>\r\n");
      out.write("                                    <td><input type=\"hidden\" name=\"continue\" id=\"continue\"\r\n");
      out.write("                                                                                   value=\"http://mail.google.com/mail/?ui=html&amp;zy=l\" />\r\n");
      out.write("                                        <input type=\"hidden\" name=\"service\" id=\"service\"\r\n");
      out.write("                                                                                   value=\"mail\" />\r\n");
      out.write("                                        <input type=\"hidden\" name=\"rm\" id=\"rm\"\r\n");
      out.write("                                                                                   value=\"false\" />\r\n");
      out.write("                                        <input type=\"hidden\" name=\"dsh\" id=\"dsh\"  value=\"-423051491917785370\" />\r\n");
      out.write("                                        <input type=\"hidden\" name=\"ltmpl2\" id=\"ltmpl\"  value=\"default\" />\r\n");
      out.write("                                        <input type=\"hidden\" name=\"ltmpl2\" id=\"ltmpl\" value=\"default\" />\r\n");
      out.write("                                        <input type=\"hidden\" name=\"scc\" id=\"scc\" value=\"1\" />\r\n");
      out.write("                                        <input type=\"hidden\" name=\"timeStmp\" id=\"timeStmp\"\r\n");
      out.write("                                                                                   value=''/>\r\n");
      out.write("                                        <input type=\"hidden\" name=\"secTok\" id=\"secTok\"\r\n");
      out.write("                                                                                   value=''/>\r\n");
      out.write("                                        <input type=\"hidden\"\r\n");
      out.write("                                                                                   name=\"GALX\"\r\n");
      out.write("                                                                                   value=\"Y5DPH5WCmOc\" />\r\n");
      out.write("                                        <input type=\"text\" name=\"uname\"  id=\"uname\"\r\n");
      out.write("                                                                                />\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                  <tr>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td align=\"left\"><div style=\"color: #666666; font-size: 75%;\"> ex: sivaji@bonu.com </div></td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                  <tr id=\"password-row\" class=\"enabled\">\r\n");
      out.write("                                    <td align=\"right\" nowrap=\"nowrap\"><span class=\"gaia le lbl\"> Password: </span> </td>\r\n");
      out.write("                                    <td><input type=\"password\" name=\"pass\" id=\"pass\"  size=\"18\" class=\"gaia le val\" />\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                  <tr>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td align=\"left\"></td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                  <tr id=\"rememberme-row\" class=\"enabled\">\r\n");
      out.write("                                    <td align=\"right\" valign=\"top\"><input type=\"checkbox\" name=\"PersistentCookie\" id=\"PersistentCookie\" value=\"yes\" />\r\n");
      out.write("                                        <input type=\"hidden\" name='rmShown' value=\"1\" />\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td><label for=\"PersistentCookie\" id=\"PersistentCookieLabel\" class=\"gaia le rem\"> Stay signed in </label>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                  <tr>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td align=\"left\"><input type=\"submit\" class=\"gaia le button\" name=\"signIn\" id=\"signIn\"\r\n");
      out.write("                                                            value=\"Sign in\"/>\r\n");
      out.write("                                    <a href=\"RegistrationaCap.jsp\">|New User?</a></td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                              </div></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 \r\n");
      out.write("                  <!-- end links box (below login box) -->\r\n");
      out.write("                </div>\r\n");
      out.write("    </table>\r\n");
      out.write("     </form>\r\n");
      out.write("    </body>\r\n");
      out.write("   </html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
