/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-09 16:25:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import java.io.*;

public final class RegistrationaCap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(5);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Address Book Registration Page</title>\r\n");
      out.write("<script language=\"javascript\" src=\"../JS/RegValidation.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"../JS/datepicker.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"../JS/NameChecked.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"displayCalendar()\" bgcolor=\"#008B8B\">\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<table >\r\n");
      out.write("	<tr ><td>\r\n");
      out.write("			<img src=\"../IMAGES/in11111dex.jpg\" width=\"100%\"></img>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table width=\"100%\">\r\n");
      out.write("	<tr ><td bgcolor=\"white\">\r\n");
      out.write("			<hr></hr>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("</table><br/></br>\r\n");
      out.write("<center><h2><font color=\"yellow\"><b>Welcome to Online Address Book Registration</b></font></h2></center>\r\n");
      out.write("\r\n");
      out.write("		<table width=\"48%\" align=\"center\" border=\"0\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>SurName</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"sname\"id=\"sname\"></td>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>Name</b></font></td>\r\n");
      out.write("				<td  width='20%'><input type=\"text\" name=\"name\" id=\"name\" onblur=\"nameChecked()\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>Qualification</b></font></td>\r\n");
      out.write("				<td width='20%'>\r\n");
      out.write("				<select name=\"qualif\"  id=\"qualif\" >\r\n");
      out.write("				<option value=\"select\">----------Select----------</option>\r\n");
      out.write("				<option value=\"SSC\">SSC</option>\r\n");
      out.write("				<option value=\"INTER\">INTER</option>\r\n");
      out.write("				<option value=\"BTech\">BTech</option>\r\n");
      out.write("				<option value=\"BSC\">BSC</option>\r\n");
      out.write("				<option value=\"MCA\">MCA</option>\r\n");
      out.write("				<option value=\"MSC\">MSC</option>\r\n");
      out.write("				<option value=\"MTech\">MTech</option>\r\n");
      out.write("				<option value=\"UG\">UG</option>\r\n");
      out.write("				<option value=\"PG\">PG</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>DOB</b></font></td>\r\n");
      out.write("				<td width='20%'>\r\n");
      out.write("				<input type=\"text\" id=\"fromDate\" name=\"fromDate\"  size=\"16\"/>		\r\n");
      out.write("					       <a href=\"javascript:calendar_startDate.toggle(document.getElementById('fromDate'));\">\r\n");
      out.write("					       <img src='../IMAGES/cal.png' width=\"20\" height=\"20\" border=\"0\" alt=\"Pick a date\"></a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table  border='0' width='48%' align=\"center\">\r\n");
      out.write("			<tr bgcolor=\"\">\r\n");
      out.write("				<td><h2><font color=\"yellow\"><b>Address Details</b></font></h2></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	\r\n");
      out.write("		<table width='48%' align='center' border='0'>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>Street</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"street\" id=\"street\"></td>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>City</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"city\" id=\"city\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>District</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"dist\" id=\"dist\" ></td>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>State</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"state\" id=\"state\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>Pin code</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"pin\" maxlength=\"6\" id=\"pin\"></td>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>Country</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"country\"  id=\"country\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>Mobile No</b></font></td>\r\n");
      out.write("				<td width='10%'><input type=\"text\" value=\"+91\" disabled size=\"2\">\r\n");
      out.write("				<input type=\"text\" name=\"mobile\" maxlength=\"10\" id=\"mobile\" size=\"13\"></td>\r\n");
      out.write("				<td width='20%'><font color=\"white\"><b>Email</b></font></td>\r\n");
      out.write("				<td width='20%'><input type=\"text\" name=\"Email\"  id=\"Email\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan='4'>&nbsp;</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			</form>\r\n");
      out.write("			<table width='48%' align='center' border='0'>\r\n");
      out.write("			<tr align=\"center\">\r\n");
      out.write("				<td colspan='4'><input type=\"submit\" value=\" submit \" onclick=\"capture()\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("				<input type=\"button\" name=\"\" value=\"Cancel\" onclick='history.back()'></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<center>\r\n");
      out.write("		<div id=\"dd\" style=\"color:white\"></div>\r\n");
      out.write("		</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
